DROP TABLE IF EXISTS region CASCADE;

DROP TABLE IF EXISTS area CASCADE;

DROP TABLE IF EXISTS classlang CASCADE;

DROP TABLE IF EXISTS classprofile CASCADE;

DROP TABLE IF EXISTS dpalevel CASCADE;

DROP TABLE IF EXISTS parentschool CASCADE;

DROP TABLE IF EXISTS registration CASCADE;

DROP TABLE IF EXISTS schooltype CASCADE;

DROP TABLE IF EXISTS studentgender CASCADE;

DROP TABLE IF EXISTS teritorytype CASCADE;

DROP TABLE IF EXISTS teritory CASCADE;

DROP TABLE IF EXISTS schooldetails CASCADE;

DROP TABLE IF EXISTS school CASCADE;

DROP TABLE IF EXISTS teststatus CASCADE;

DROP TABLE IF EXISTS testsubject CASCADE;

DROP TABLE IF EXISTS testyear CASCADE;

DROP TABLE IF EXISTS testlanguage CASCADE;

DROP TABLE IF EXISTS student CASCADE;

DROP TABLE IF EXISTS test CASCADE;